export const many = [
  "Ask_Me_Now_(Monk).mid",
  "Baby_It's_Cold_Outside.mid",
  "ButNotForMeV2.mid",
  "CloseEnoughForLovePa.719.mid",
  "Come_Rain_Or_Come_Shine_(duet).mid",
  "Desire.mid",
  "Easy_Living_4.mid",
  "Emily_(tk_2).mid",
  "Gaviota_trio_2.mid",
  "GoodBaitPiano.mid",
  "Good_Bait.mid",
  "Have_You_Met_Miss_Jones_(duet).mid",
  "HowDoYouKeepTheMusic.mid",
  "I'm_Old_Fashioned_(trio)_[M].mid",
  "ILoveYouexbiab.mid",
  "I_Could_Write_A_Book.mid",
  "ImGettingSentimental.mid",
  "Just_Friends_(trio).mid",
  "Louisiana.mid",
  "Maid(en)s_Of_Cadiz.mid",
  "Manteca.mid",
  "MemoriesofParis.mid",
  "MonaLisa.mid",
  "My_Funny_Valentine.mid",
  "NightMistBlues4.mid",
  "Once_Upon_A_Summertime.mid",
  "Our_Love_Is_Here_To_Stay_(trio).mid",
  "Recordame.mid",
  "Remember935.mid",
  "Shiny_Stockings.mid",
  "Since_We_Met.mid",
  "Soon.mid",
  "Stars_Fell_On_Alabama_(duet).mid",
  "Strange_Meadowlark.mid",
  "Surrey-Beautiful_Medley.mid",
  "TheShiningSea.mid",
  "Theme_From_Spartacus.mid",
  "There_Will_Never_Be_Another_You.mid",
  "TheyDidntBelieveMePa.1025.mid",
  "Waltz_For_Dave.mid",
  "We_Will_Meet_Again.mid",
  "While_We're_Young.mid",
  "goodbaitGM.mid",
];

export const garbage = [
  "Brazillike_2.mid",
  "Brazillike_backing.mid",
  "dolphindance3_no_pia.mid",
];

export const piano = [
  "Nardis900.mid",
  "Nardis_(Miles_Davis-.mid",
  "NatureBoyTrio.mid",
];

export const muxed = ["Caravan2exBIAB.mid", "Look_For_the_Silver_.mid"];
